### ISSUE TITLE
STATUS_NOT_SUPPORTED description faulty

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1023]
> STATUS_NOT_SUPPORTED  The file system does not support per-stream contexts for this file stream.

per-stream contexts?  Or per-stream contexts *and* something else (for instance won't you get this back if FileObject->FsContext2 is null?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 661dc134-595d-d002-2e38-88dbf5019333
* Version Independent ID: fb62151f-3bdd-af91-e1ed-7c33c571a424
* Content: [FltSetStreamHandleContext function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltsetstreamhandlecontext)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltsetstreamhandlecontext.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltsetstreamhandlecontext.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , I've updated the page to reflect one additional NOT_SUPPORTED scenario close to the one you mention in this issue.  As you're likely aware, it's very common that we don't document an exhaustive list of error conditions in WDK docs (and other docs), because the source code is wide and deep across many modules. To your point, the dev team says that FltSetStreamHandleContext does not currently use FsContext2 as the per-handle structure.
