### ISSUE TITLE
Not: Any chance that the parameters can be clarified

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1181]
I know that this is create from the macro which for no good reason uses A1 to A11, but it would be nice to locally override.

Better still get someone to fix the macro so that it uses better names. Even `_FILELOCK_` would be better that `A1` (and it would help in VS because of intellisense.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93a56b3-b784-779e-fd3a-460599f55bfc
* Version Independent ID: f4bd5c2a-0667-a128-b9c7-529580f79664
* Content: [FsRtlFastLock macro (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlfastlock?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(STRUCTS%252F_ISOL_CONTEXT%253A%253AFsRtlFastLock);k(_ISOL_CONTEXT%253A%253AFsRtlFastLock);k(FsRtlFastLock);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlfastlock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlfastlock.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , I added descriptive names for each parameter, as well as SAL annotations, to this page - hope this helps. I agree that meaningful names would be helpful. I sent email to the team, but doubt that they'll be able to prioritize it. And we avoid manual syntax overrides because that can result in outdated syntax blocks when the code base changes.
