### ISSUE TITLE
What the request type is?

### ISSUE THREAD

**Issue by Itsaniceday** [MicrosoftDocs/windows-driver-docs-ddi#1397]
Hi guys,

I have a issue how can I know what the I/O request of a major function code and a minor function code?
if comment it out, I think it will be helpful for the development.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad2209db-5fde-c8b1-3ecc-72dbd29bdb4e
* Version Independent ID: 71dfa3a9-ef58-c66f-c624-4079af0fe995
* Content: [EVT_IDD_CX_MONITOR_I2C_TRANSMIT (iddcx.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nc-iddcx-evt_idd_cx_monitor_i2c_transmit)
* Content Source: [wdk-ddi-src/content/iddcx/nc-iddcx-evt_idd_cx_monitor_i2c_transmit.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/iddcx/nc-iddcx-evt_idd_cx_monitor_i2c_transmit.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@Itsaniceday, I'm going to close this issue since it appears you're looking for support versus reporting a documentation issue. Please reopen this issue with clarification if I'm misunderstanding. Otherwise, you can ask your question on [Windows Hardware Q&A](https://learn.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html) or an [OSR forum](https://community.osr.com/).
