### ISSUE TITLE
Return value section says "none" when the macro actually returns BOOL

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/windows-driver-docs-ddi#1426]
[Enter feedback here]
Return value section says "none" when the macro actually returns BOOL. While the Remarks section describes the return value, it would be better if the Return value section is updated appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d66bcef4-c694-d12e-b535-90f2aec47748
* Version Independent ID: 3e6a4e85-ee54-baa4-fd08-7b04fe0bb6e2
* Content: [RtlEqualMemory macro (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlequalmemory)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlequalmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlequalmemory.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Good find @hwisungi thanks for letting us know.

Due to the constraints of our publishing system, the best we can do in this case is to remove the Returns section entirely from the page in question.  I have done this -- see https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlequalmemory.

Thanks again for caring about the docs :)
