### ISSUE TITLE
Getting Error Code 50

### ISSUE THREAD

**Issue by salih-okur** [MicrosoftDocs/windows-driver-docs-ddi#1435]
[Enter feedback here]
Hello,
I am trying to send sd command to sd card by using sffdisk.h header file from user mode application. With IOCTL_SFFDISK_DEVICE_COMMAND ı am getting error code 50 from getLastError function.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1feb1412-e75c-9782-a850-e806993d0707
* Version Independent ID: 87d8f253-6eb3-27e2-8f61-361730b9c1fa
* Content: [Sffdisk.h header - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/sffdisk/)
* Content Source: [wdk-ddi-src/content/sffdisk/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/sffdisk/index.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @salih-okur - you can find the meaning of error code 50 on [this page](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) - says your request is not supported. Issues filed in this repo are for documentation related to Windows driver development. I'm closing your issue since you didn't mention a doc issue. Let me know if you do have a documentation issue and I'll reopen it!
