### ISSUE TITLE
_HIDP_PREPARSED_DATA structure

### ISSUE THREAD

**Issue by Kinkyboo** [MicrosoftDocs/windows-driver-docs-ddi#1440]
[Enter feedback here]
All links to the [_HIDP_PREPARSED_DATA](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getpreparseddata) points to the page for HidD_GetPreparsedData function (hidsdi.h). Thus it's impossible to know how _HIDP_PREPARSED_DATA is constructed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: affec3d7-565b-c71c-9e26-088760ab74a1
* Version Independent ID: 59e81dc7-a6a3-716c-7948-0c0a433e3920
* Content: [HidD_GetPreparsedData function (hidsdi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getpreparseddata)
* Content Source: [wdk-ddi-src/content/hidsdi/nf-hidsdi-hidd_getpreparseddata.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/hidsdi/nf-hidsdi-hidd_getpreparseddata.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @Kinkyboo,

Thank you for contacting us with your question.

The \_HIDP_PREPARSED_DATA structure is opaque, by design. You can use the **HidP_\*** methods defined in the [hidpi.h header](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/) to interact with the values from a \_HIDP_PREPARSED_DATA structure returned by the [HidD_GetPreparsedData function](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getpreparseddata).

For more information, see the [Preparsed Data](https://learn.microsoft.com/windows-hardware/drivers/hid/preparsed-data) article. I hope this helps.

Thanks,
 ~ *Mark*
