### ISSUE TITLE
Packet Injection Functions Links Broken?

### ISSUE THREAD

**Issue by NoelStephens** [MicrosoftDocs/windows-driver-docs-ddi#159]
All links to the Packet Injection Functions page lands you back to this page.  
Is this by design or is the link reference itself broken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1216e0-f3b6-414e-2aad-b7ba031c3c12
* Version Independent ID: f4160c82-4653-fde5-4331-14ad404f9936
* Content: [FWPS_INJECT_COMPLETE0](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fwpsk/nc-fwpsk-fwps_inject_complete0)
* Content Source: [wdk-ddi-src/content/fwpsk/nc-fwpsk-fwps_inject_complete0.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/nc-fwpsk-fwps_inject_complete0.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @NoelStephens , good catch! Nope, it's not by design. :) I've fixed all references to that link across the references pages so they should point to the [correct page](https://docs.microsoft.com/windows-hardware/drivers/network/packet-injection-functions
). That change should be live later today. Thanks for finding this!
