### ISSUE TITLE
FwpsInjectMacSendAsync Documentation is FwpsInjectMacReceiveAsync Documentation

### ISSUE THREAD

**Issue by NoelStephens** [MicrosoftDocs/windows-driver-docs-ddi#167]
I read through the closed notes on this running issue with the documentation.  Could someone fix the documentation on this as this method is a "mish-mash" of a copy-paste from the FwpsInjectMacReceiveAsync function...but this is the page for the documentation of the FwpsInjectMacSendAsync function.   Additionally, there appears to still be some question behind the send vs receive buffer retreat discussed in the closed feedback attached to this page.
Driver development is hard enough by itself...but when the documentation is not accurate it makes it very hard to discern between what is the correct usage.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd93606-22dc-f6d6-cef5-f4324b7dcc63
* Version Independent ID: 3aeb627c-7a54-970a-4c80-943d068876e3
* Content: [FwpsInjectMacSendAsync0 function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fwpsk/nf-fwpsk-fwpsinjectmacsendasync0)
* Content Source: [wdk-ddi-src/content/fwpsk/nf-fwpsk-fwpsinjectmacsendasync0.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/nf-fwpsk-fwpsinjectmacsendasync0.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
OK, I've gotten this all cleared up. You were indeed correct that this page referenced the Receive API instead of the Send. I've fixed that goof, and the changes should be live later today. While I was investigating, I got confirmation from one of the senior engineers that this page is otherwise accurate and is consistent with how the rest of the APIs are documented. In code, the APIs are called the same way except for the NBL offset, which is why the information is the same on both. So that much is by design.

Thanks for pointing this out and helping clarify the docs!
