### ISSUE TITLE
Links missing

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#317]
Why aren't there links to the typedefs for the members of the structure? Why do we have to perform multiple searches to get the definition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efb8f3a-c66f-994c-eedc-67e603559d18
* Version Independent ID: cee7f715-77f6-72bf-598f-10573135dac5
* Content: [_FAST_IO_DISPATCH - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_fast_io_dispatch)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_fast_io_dispatch.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_fast_io_dispatch.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Great question @BrianCatlin, sorry for the delay getting back to you.  Those callbacks are indeed in wdm.h, but we do not currently have doc pages for them.  I've opened an internal task to track that.  In the meantime, I found this article from 1996 that describes them all!  

https://www.osronline.com/article.cfm%5Eid=166.htm

Closing out this issue for now since we're tracking this separately.
