### ISSUE TITLE
Incorrect status code returned by ZwCreateKeyTransacted

### ISSUE THREAD

**Issue by TomaszNowakSanDiego** [MicrosoftDocs/windows-driver-docs-ddi#34]
Here's the error scenario:
Key doesn't exist.
ZwCreateKeyTransacted is called with transaction handle from thread one. It returns STATUS_SUCCESS. Transaction remains pending.

ZwCreateKeyTransacted is called with transaction handle from thread two. It returns STATUS_OBJECT_NAME_NOT_FOUND. This suggest parent key doesn't exist (but it does).
 IMHO STATUS_TRANSACTIONAL_CONFLICT should be returned instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd7bb29b-b71a-9df4-5c8c-8cdc2463e35d
* Version Independent ID: afd71f2a-32c0-a711-f011-29c40d3059eb
* Content: [ZwCreateKeyTransacted function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwcreatekeytransacted)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwcreatekeytransacted.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwcreatekeytransacted.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello,

Thanks for the feedback. If a key is not visible within your view of the registry (but is visible in another view) then the call returns STATUS_OBJECT_NAME_NOT_FOUND.

I have forwarded your comment to the Windows Kernel team about returning a more appropriate error code related to creating a key that is not visible in a transaction because it was created in another pending transaction. They are definitely considering your comment to make improvements.

Thanks again for pointing this out,

PageWriter
