### ISSUE TITLE
Need details on module names

### ISSUE THREAD

**Issue by bendono** [MicrosoftDocs/windows-driver-docs-ddi#369]
The documentation is missing important details on

1. What kind of module names to match on
2. Case sensitivity of module names.

Regarding 1), `GetModuleNameString` defines multiple module names: `DEBUG_MODNAME_IMAGE`, `DEBUG_MODNAME_MODULE`, `DEBUG_MODNAME_LOADED_IMAGE,` `DEBUG_MODNAME_SYMBOL_FILE`, and `DEBUG_MODNAME_MAPPED_IMAGE`. With a bit of experimentation, it seems that this `GetModuleByModuleName2Wide` matches against `DEBUG_MODNAME_MODULE` only.

Regarding 2), it seems that this is case insensitive. This information should be included in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 870245e1-7cd8-fff8-9386-b3b27317911a
* Version Independent ID: f5968336-a591-e034-429e-b8095afe3271
* Content: [IDebugSymbols3::GetModuleByModuleName2Wide (dbgeng.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dbgeng/nf-dbgeng-idebugsymbols3-getmodulebymodulename2wide)
* Content Source: [wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugsymbols3-getmodulebymodulename2wide.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugsymbols3-getmodulebymodulename2wide.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Sorry for the length delay @bendono. I was unable to track down any additional information on adding module name details for the debugger extensions.

Over the last year, we have fixed some issues with the reference topics to include more information, but I don't think this was the issue here that you describe.

If it's still an issue, you may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
•	[OSR's ntdev List](https://community.osr.com/categories/ntdev)
•	[OSR's windbg List](https://community.osr.com/categories/windbg)

You might also check the use of engextcpp, as I believe it uses dbgeng underneath.
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/engextcpp-extension-design-guide

Thanks again for reaching out and good luck with your work.
