### ISSUE TITLE
Warning banner

### ISSUE THREAD

**Issue by GabeSJones** [MicrosoftDocs/windows-driver-docs-ddi#436]
This function (and related functions) shipped in the fall, so the warning banner about "prerelease product" should no longer apply, yes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d37f78-26d5-a983-8432-4fbfaf98a168
* Version Independent ID: f06126de-8760-192c-190b-491ec6b14011
* Content: [NdisSetNblTimestampInfo function (ndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nf-ndis-ndissetnbltimestampinfo)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndissetnbltimestampinfo.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndissetnbltimestampinfo.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @GabeSJones, thanks for the feedback. Your sharp eye is appreciated. In this case, the banner is currently technically applicable because this feature is only used by internal components in the operating system and is not available for public use. It is included in the WDK as of Windows 10, version 1809, but the feature is not fully released to the public yet; hence, the banner. This is something we do on occasion when something is still baking. For example, the same banner exists on the [NetAdapterCx](https://docs.microsoft.com/en-us/windows-hardware/drivers/netcx/) docs. That technology, while available for the public to use if they so desired, is still under active development and is not a stable release as of the time of writing. The same goes for this function. In the future, we'll remove the banner if the feature becomes ready for public consumption.

Hope this helps!
