### ISSUE TITLE
Return value

### ISSUE THREAD

**Issue by eriklangemeijer** [MicrosoftDocs/windows-driver-docs-ddi#49]
Document states no return value. Return value should be "The function returns the resulting decremented value." like InterlockedDecrement function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc8b58d6-3c46-a049-35c8-fa8be3fe2065
* Version Independent ID: 0e8b2b88-5fa3-ab30-8cf8-0219d6f3cba0
* Content: [NdisInterlockedDecrement macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nf-ndis-ndisinterlockeddecrement#feedback)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndisinterlockeddecrement.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndisinterlockeddecrement.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @eriklangemeijer , good catch. Since NdisInterlockedDecrement is a wrapper around InterlockedDecrement, the syntax generator for the page thought it was a void return value because the true definition didn't follow the #define. I've updated the page to reflect the correct wording and the change should be live soon. Thanks!
