### ISSUE TITLE
Parameter names/order are incorrect

### ISSUE THREAD

**Issue by mebersol** [MicrosoftDocs/windows-driver-docs-ddi#587]
RtlRunOnceExecuteOnce and RTL_RUN_ONCE_INIT_FN callback function have wrong parameter names/order for Parameter/Context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd6a73c-fc1e-2589-d8bb-9dee07c6ea0e
* Version Independent ID: fc767e67-c0b5-79be-c693-6d8fd746c1a5
* Content: [RTL_RUN_ONCE_INIT_FN (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nc-ntddk-rtl_run_once_init_fn#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nc-ntddk-rtl_run_once_init_fn.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nc-ntddk-rtl_run_once_init_fn.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @mebersol thanks for the report, and apologies for the delay.  It turns out this is an internal bug that we are tracking.  I was able to force the syntax block to render properly using the above commit, but the descriptions of those two parameters are still reversed due to the bug.  I don't have an ETA for that fix right now.

Thanks again for your interest in the docs!
