### ISSUE TITLE
RtlGetCompressionWorkSpaceSize() with COMPRESSION_ENGINE_MAXIMUM returns 0xc000000d

### ISSUE THREAD

**Issue by Grabelkovsky** [MicrosoftDocs/windows-driver-docs-ddi#605]
When I tried RtlGetCompressionWorkSpaceSize with COMPRESSION_ENGINE_MAXIMUM, API returns 0xC000000D - STATUS_INVALID_PARAMETER!?!

When I tried after COMPRESSION_FORMAT_LZNT1 - status SUCCESS.

My opinion, it's documentation error or API error.

Regards,
Dr. Michael Grabelkovsky.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedaa724-28b6-001f-b250-6657476601ae
* Version Independent ID: 6893d696-7d1e-d3fd-294a-8a09ea2b3e76
* Content: [RtlGetCompressionWorkSpaceSize function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlgetcompressionworkspacesize)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-rtlgetcompressionworkspacesize.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlgetcompressionworkspacesize.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@Grabelkovsky , you need to bitwise-OR a supported compression format along with COMPRESSION_ENGINE_MAXIMUM; otherwise, you will get STATUS_INVALID_PARAMETER. Looking at the format and engine values in ntifs.h, you'll see that sending COMPRESSION_FORMAT_LZNT1 only is equivalent to (COMPRESSION_FORMAT_LZNT1 | COMPRESSION_ENGINE_STANDARD). See the description of the CompressionFormatAndEngine parameter for full details. Let me know if you have further questions!
