### ISSUE TITLE
Unclear unit for Address

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs-ddi#694]
The Address field doesn't state what unit it is in or how to interpret the data. Not even cross referencing T10/1363-D is enough, since that document says that there are two possible formats and there is no way to know here which format is being used since the format selector is not part of any input buffer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42034ec-9d25-c584-6f80-f9e734cff332
* Version Independent ID: 890cb372-5a6c-eff2-3bb5-0f45f5ed2971
* Content: [_TRACK_DATA (ntddcdrm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddcdrm/ns-ntddcdrm-_track_data)
* Content Source: [wdk-ddi-src/content/ntddcdrm/ns-ntddcdrm-_track_data.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddcdrm/ns-ntddcdrm-_track_data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@henke37 , thanks for submitting this issue. Apologies that I cannot add explicit spec section references to our pages. I did remove the "Revision" since it was out of date (hence why we can't add explicit references). I also added a link to the associated IOCTL. TRACK_DATA is a substructure of the output CDROM_TOC or CDROM_TOC_SESSION_DATA structure when IOCTL_CDROM_READ_TOC_EX is issued with an input CDROM_READ_TOC_EX.Format of CDROM_READ_TOC_EX_FORMAT_TOC or CDROM_READ_TOC_EX_FORMAT_SESSION respectively.

Within the T10/1363-D spec, TOC READ is explained in the 5.23 READ TOC/PMA/ATIP Command section. This section describes ADR and specifies that possible values are in Table 221. The actual encoding is described in 4.2.3.4 Q Sub-channel in the Program Area.

Hope this helps!
