### ISSUE TITLE
Very poor description

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs-ddi#711]
The description omits significant details. If the function must write a pin name string to the memory pointed by the "Data" argument, there must be a size limit. It's not clear why argument type is PVOID instead of PWSTR. The function is provided with the IRP pointer, but it's unclear whether the IRP matches KSPROPERTY_PIN_NAME request or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd98a086-c557-bd23-86fd-4b5eb44a54fb
* Version Independent ID: be984e78-eed7-4ced-5a9e-65ebc1b25627
* Content: [IPinName::GetPinName (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-ipinname-getpinname)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-ipinname-getpinname.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-ipinname-getpinname.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@emuzychenko - Thanks for this input on the portcls IPinName::GetPinName method. I added links to the other supporting topics such as IPinName, Filter, Pin, and Node Properties and Pin Factories as well as to the IRP topic I/O request packets. I believe the specific use of pin request would depend on the goals of your driver. I normally look to the sysvad sample for usage examples. It looks like in Sysvad, other techniques are used to work with pin names instead of IPinName::GetPinName. So I would look in Sysvad for the type of work that you are doing with pins. For example this code is from micintopo.cpp that is working with a PinId.

```cpp
    ULONG                   nPinId = (ULONG)-1;
      
    if (PropertyRequest->InstanceSize >= sizeof(ULONG))
    {
        nPinId = *(PULONG(PropertyRequest->Instance));

        if ((nPinId < cJackDescriptions) && (JackDescriptions[nPinId] != NULL)) ```
```

If you are still working with pins, I would recommend posting the code that you have tried and what you are trying to achieve to one of the forums, such as those provided by OSR -[OSR's ntdev List](https://community.osr.com/categories/ntdev) or [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html).

Thanks again for this input, and good luck with your WDM kernel mode audio driver development.
