### ISSUE TITLE
RtlULongLongToLongLong  return value documentation is incorrect. 

### ISSUE THREAD

**Issue by bgianfo** [MicrosoftDocs/windows-driver-docs-ddi#938]
The documentation for RtlULongLongToLongLong states there is no return value, when it returns NTSTATUS in the signature? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5482baf4-6375-1e28-2031-5cc83d4b767f
* Version Independent ID: 33416e02-4afd-7bad-9743-62bfa0f9db6f
* Content: [RtlULongLongToLongLong function (ntintsafe.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntintsafe/nf-ntintsafe-rtlulonglongtolonglong)
* Content Source: [wdk-ddi-src/content/ntintsafe/nf-ntintsafe-rtlulonglongtolonglong.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntintsafe/nf-ntintsafe-rtlulonglongtolonglong.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report @bgianfo 

I noticed that the same is true for every function page in the `ntintsafe.h` header, https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntintsafe.

I just pushed an update for all of them that says returns success or check the header for error values (since they are all inline).  It looks like 2/3 of them return STATUS_INTEGER_OVERFLOW (including the one you reference) but not all.

Update should be on the live site within an hour or so.
