### ISSUE TITLE
OpenEvent returns 2 if event name is not prefixed with Global\\ on windows 7 ( x64)

### ISSUE THREAD

**Issue by seedkar1** [MicrosoftDocs/windows-driver-docs-ddi#942]
\\\\BaseNamedObjects\\\\Xxx could only be opened under the name Global\\\\Xxx in user mode on Windows 7 (x64)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e9ef9d-c821-66a5-add5-ca2889a4b299
* Version Independent ID: 23767e29-a42c-3703-24a0-ce8d6c354d22
* Content: [IoCreateNotificationEvent function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iocreatenotificationevent)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iocreatenotificationevent.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iocreatenotificationevent.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback @seedkar1 

You are exactly right.  If you're accessing from session 0, you can use `BaseNamedObjects\Xxx` but from other sessions you would need the `Global\Xxx` format because Global is a symlink and will give you the expected result regardless of session. 

I've updated the doc - that fix should appear on the live site within an hour or so.
